name: sysmac_generator
description: A simple command-line application.
version: 1.0.0
homepage: https://github.com/nils-ten-hoeve/sysmac_generator
documentation: https://github.com/nils-ten-hoeve/sysmac_generator/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  collection: ^1.15.0
  archive: ^3.6.1
  fluent_regex: ^1.0.3
  xml: ^5.3.1
  documentation_builder: ^0.0.11
  recase: ^4.0.0
  petitparser: ^4.4.0
  logging: ^1.0.2
  
dev_dependencies:
  test: ^1.19.2
  build_runner: ^2.1.7
  lints: ^6.0.0
  shouldly: ^0.5.0+1

executables:
  sysmac_generator: sysmac_generator
